package com.example.demo.flatbuffer;// automatically generated by the FlatBuffers compiler, do not modify

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FbAction extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static FbAction getRootAsFbAction(ByteBuffer _bb) { return getRootAsFbAction(_bb, new FbAction()); }
  public static FbAction getRootAsFbAction(ByteBuffer _bb, FbAction obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FbAction __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FbObject object() { return object(new FbObject()); }
  public FbObject object(FbObject obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createFbAction(FlatBufferBuilder builder,
      int objectOffset) {
    builder.startTable(1);
    FbAction.addObject(builder, objectOffset);
    return FbAction.endFbAction(builder);
  }

  public static void startFbAction(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addObject(FlatBufferBuilder builder, int objectOffset) { builder.addOffset(0, objectOffset, 0); }
  public static int endFbAction(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FbAction get(int j) { return get(new FbAction(), j); }
    public FbAction get(FbAction obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

