package com.example.demo.flatbuffer;// automatically generated by the FlatBuffers compiler, do not modify

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FbCharacter extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static FbCharacter getRootAsFbCharacter(ByteBuffer _bb) { return getRootAsFbCharacter(_bb, new FbCharacter()); }
  public static FbCharacter getRootAsFbCharacter(ByteBuffer _bb, FbCharacter obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FbCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String uid() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer uidAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer uidInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public FbObject objects(int j) { return objects(new FbObject(), j); }
  public FbObject objects(FbObject obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int objectsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public FbObject.Vector objectsVector() { return objectsVector(new FbObject.Vector()); }
  public FbObject.Vector objectsVector(FbObject.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createFbCharacter(FlatBufferBuilder builder,
      int uidOffset,
      int objectsOffset) {
    builder.startTable(2);
    FbCharacter.addObjects(builder, objectsOffset);
    FbCharacter.addUid(builder, uidOffset);
    return FbCharacter.endFbCharacter(builder);
  }

  public static void startFbCharacter(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addUid(FlatBufferBuilder builder, int uidOffset) { builder.addOffset(0, uidOffset, 0); }
  public static void addObjects(FlatBufferBuilder builder, int objectsOffset) { builder.addOffset(1, objectsOffset, 0); }
  public static int createObjectsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startObjectsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endFbCharacter(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FbCharacter get(int j) { return get(new FbCharacter(), j); }
    public FbCharacter get(FbCharacter obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

