package com.example.demo.flatbuffer;// automatically generated by the FlatBuffers compiler, do not modify

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FbChat extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static FbChat getRootAsFbChat(ByteBuffer _bb) { return getRootAsFbChat(_bb, new FbChat()); }
  public static FbChat getRootAsFbChat(ByteBuffer _bb, FbChat obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FbChat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String cid() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer cidAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer cidInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String oid() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer oidAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer oidInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String content() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer contentAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer contentInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createFbChat(FlatBufferBuilder builder,
      int cidOffset,
      int oidOffset,
      int contentOffset) {
    builder.startTable(3);
    FbChat.addContent(builder, contentOffset);
    FbChat.addOid(builder, oidOffset);
    FbChat.addCid(builder, cidOffset);
    return FbChat.endFbChat(builder);
  }

  public static void startFbChat(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addCid(FlatBufferBuilder builder, int cidOffset) { builder.addOffset(0, cidOffset, 0); }
  public static void addOid(FlatBufferBuilder builder, int oidOffset) { builder.addOffset(1, oidOffset, 0); }
  public static void addContent(FlatBufferBuilder builder, int contentOffset) { builder.addOffset(2, contentOffset, 0); }
  public static int endFbChat(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FbChat get(int j) { return get(new FbChat(), j); }
    public FbChat get(FbChat obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

