package com.example.demo.flatbuffer;// automatically generated by the FlatBuffers compiler, do not modify

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FbItem extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FbItem __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long tid() { return bb.getLong(bb_pos + 0); }
  public long amount() { return bb.getLong(bb_pos + 8); }

  public static int createFbItem(FlatBufferBuilder builder, long tid, long amount) {
    builder.prep(8, 16);
    builder.putLong(amount);
    builder.putLong(tid);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FbItem get(int j) { return get(new FbItem(), j); }
    public FbItem get(FbItem obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

