package com.example.demo.flatbuffer;// automatically generated by the FlatBuffers compiler, do not modify

public final class FbMethod {
  private FbMethod() { }
  public static final byte N = 0;
  public static final byte C = 1;
  public static final byte R = 2;
  public static final byte U = 3;
  public static final byte D = 4;

  public static final String[] names = { "N", "C", "R", "U", "D", };

  public static String name(int e) { return names[e]; }
}

