package com.example.demo.flatbuffer;// automatically generated by the FlatBuffers compiler, do not modify

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FbMessage extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static FbMessage getRootAsFbMessage(ByteBuffer _bb) { return getRootAsFbMessage(_bb, new FbMessage()); }
  public static FbMessage getRootAsFbMessage(ByteBuffer _bb, FbMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FbMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte method() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte result() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte payloadType() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table payload(Table obj) { int o = __offset(10); return o != 0 ? __union(obj, o + bb_pos) : null; }

  public static int createFbMessage(FlatBufferBuilder builder,
      byte method,
      byte result,
      byte payload_type,
      int payloadOffset) {
    builder.startTable(4);
    FbMessage.addPayload(builder, payloadOffset);
    FbMessage.addPayloadType(builder, payload_type);
    FbMessage.addResult(builder, result);
    FbMessage.addMethod(builder, method);
    return FbMessage.endFbMessage(builder);
  }

  public static void startFbMessage(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addMethod(FlatBufferBuilder builder, byte method) { builder.addByte(0, method, 0); }
  public static void addResult(FlatBufferBuilder builder, byte result) { builder.addByte(1, result, 0); }
  public static void addPayloadType(FlatBufferBuilder builder, byte payloadType) { builder.addByte(2, payloadType, 0); }
  public static void addPayload(FlatBufferBuilder builder, int payloadOffset) { builder.addOffset(3, payloadOffset, 0); }
  public static int endFbMessage(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishFbMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedFbMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FbMessage get(int j) { return get(new FbMessage(), j); }
    public FbMessage get(FbMessage obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

