package com.example.demo.flatbuffer;// automatically generated by the FlatBuffers compiler, do not modify

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FbObject extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static FbObject getRootAsFbObject(ByteBuffer _bb) { return getRootAsFbObject(_bb, new FbObject()); }
  public static FbObject getRootAsFbObject(ByteBuffer _bb, FbObject obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FbObject __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String oid() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer oidAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer oidInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String name() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public byte type() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte state() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public FbVec3 pos() { return pos(new FbVec3()); }
  public FbVec3 pos(FbVec3 obj) { int o = __offset(12); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }

  public static void startFbObject(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addOid(FlatBufferBuilder builder, int oidOffset) { builder.addOffset(0, oidOffset, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(1, nameOffset, 0); }
  public static void addType(FlatBufferBuilder builder, byte type) { builder.addByte(2, type, 0); }
  public static void addState(FlatBufferBuilder builder, byte state) { builder.addByte(3, state, 0); }
  public static void addPos(FlatBufferBuilder builder, int posOffset) { builder.addStruct(4, posOffset, 0); }
  public static int endFbObject(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FbObject get(int j) { return get(new FbObject(), j); }
    public FbObject get(FbObject obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

