package com.example.demo.flatbuffer;// automatically generated by the FlatBuffers compiler, do not modify

public final class FbResult {
  private FbResult() { }
  public static final byte S = 0;
  public static final byte E = 1;

  public static final String[] names = { "S", "E", };

  public static String name(int e) { return names[e]; }
}

