package com.example.demo.flatbuffer;// automatically generated by the FlatBuffers compiler, do not modify

public final class FbState {
  private FbState() { }
  public static final byte I = 0;
  public static final byte M = 1;
  public static final byte A = 2;
  public static final byte D = 3;
  public static final byte S = 4;

  public static final String[] names = { "I", "M", "A", "D", "S", };

  public static String name(int e) { return names[e]; }
}

