package com.example.demo.fb;// automatically generated by the FlatBuffers compiler, do not modify

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Chat extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static Chat getRootAsChat(ByteBuffer _bb) { return getRootAsChat(_bb, new Chat()); }
  public static Chat getRootAsChat(ByteBuffer _bb, Chat obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Chat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Object object() { return object(new Object()); }
  public Object object(Object obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public String content() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer contentAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer contentInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createChat(FlatBufferBuilder builder,
      int objectOffset,
      int contentOffset) {
    builder.startTable(2);
    Chat.addContent(builder, contentOffset);
    Chat.addObject(builder, objectOffset);
    return Chat.endChat(builder);
  }

  public static void startChat(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addObject(FlatBufferBuilder builder, int objectOffset) { builder.addOffset(0, objectOffset, 0); }
  public static void addContent(FlatBufferBuilder builder, int contentOffset) { builder.addOffset(1, contentOffset, 0); }
  public static int endChat(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Chat get(int j) { return get(new Chat(), j); }
    public Chat get(Chat obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

