package com.example.demo.fb;// automatically generated by the FlatBuffers compiler, do not modify

public final class Payload {
  private Payload() { }
  public static final byte NONE = 0;
  public static final byte Chat = 1;
  public static final byte Action = 2;
  public static final byte Field = 3;

  public static final String[] names = { "NONE", "Chat", "Action", "Field", };

  public static String name(int e) { return names[e]; }
}

