package com.example.demo.fb;// automatically generated by the FlatBuffers compiler, do not modify

public final class State {
  private State() { }
  public static final byte I = 0;
  public static final byte M = 1;
  public static final byte A = 2;

  public static final String[] names = { "I", "M", "A", };

  public static String name(int e) { return names[e]; }
}

