package com.example.demo.fb;// automatically generated by the FlatBuffers compiler, do not modify

public final class Type {
  private Type() { }
  public static final byte P = 0;
  public static final byte N = 1;
  public static final byte O = 2;

  public static final String[] names = { "P", "N", "O", };

  public static String name(int e) { return names[e]; }
}

